#!/bin/bash
# Common report generation script for GHAW workflows
# This script generates standardized review reports and statistics

set -e

# Configuration (can be overridden by environment variables)
MAX_LINES="${MAX_LINES:-50}"
REPORT_TITLE="${REPORT_TITLE:-Review Report}"
REPORT_FILE="${REPORT_FILE:-combined-report.md}"
STATS_FILE="${STATS_FILE:-review-stats.txt}"

# Function to log messages
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >&2
}

# Function to generate a basic combined report
generate_basic_report() {
    local reviews=("$@")
    
    log "Generating basic report for reviews: ${reviews[*]}"
    
    cat > "$REPORT_FILE" << EOF
# ${REPORT_TITLE}

Generated on $(date)

EOF

    for review in "${reviews[@]}"; do
        local result_file="${review}-review-results.txt"
        echo "## ${review^} Review Results" >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
        
        if [ -f "$result_file" ]; then
            echo '```' >> "$REPORT_FILE"
            head -n "$MAX_LINES" "$result_file" >> "$REPORT_FILE"
            echo '```' >> "$REPORT_FILE"
            log "✅ Added ${review} results ($(wc -l < "$result_file" 2>/dev/null || echo 0) lines)"
        else
            echo "${review^} review failed or did not produce results." >> "$REPORT_FILE"
            log "❌ Missing results for ${review}"
        fi
        echo "" >> "$REPORT_FILE"
    done
    
    log "Basic report generated: $REPORT_FILE"
}

# Function to generate multi-stream report (for comprehensive reviews)
generate_multistream_report() {
    local -A streams
    streams["Security & Compliance"]="security compliance safety"
    streams["Code Quality"]="readability efficiency performance"
    streams["Architecture"]="architecture scalability modularity" 
    streams["User Experience"]="usability accessibility documentation"
    streams["Cross-Stream"]="reliability testability maintainability compatibility"
    
    log "Generating multi-stream report"
    
    cat > "$REPORT_FILE" << EOF
# 🤯 Comprehensive Review Multi-Stream Report

Generated on $(date)

## 🌊 Multi-Stream Pipeline Architecture

This review uses a **sophisticated multi-stream parallel architecture**:

### 🔒 Security & Compliance Stream
Security → Compliance → Safety

### 📖 Code Quality Stream  
Readability → Efficiency → Performance

### 🏗️ Architecture Stream
Architecture → Scalability → Modularity

### 👤 User Experience Stream
Usability → Accessibility → Documentation

### 🔀 Cross-Stream Convergence
Multi-stream dependencies create sophisticated quality gates

EOF

    for stream in "${!streams[@]}"; do
        echo "## 🌊 $stream Stream Results" >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
        
        for review in ${streams[$stream]}; do
            local result_file="${review}-review-results.txt"
            echo "### 🔍 ${review^} Review" >> "$REPORT_FILE"
            
            if [ -f "$result_file" ]; then
                echo '```' >> "$REPORT_FILE"
                head -n "$MAX_LINES" "$result_file" >> "$REPORT_FILE"
                echo '```' >> "$REPORT_FILE"
                log "✅ Added ${review} results"
            else
                echo "❌ ${review^} review failed or did not produce results." >> "$REPORT_FILE"
                log "❌ Missing results for ${review}"
            fi
            echo "" >> "$REPORT_FILE"
        done
    done
    
    cat >> "$REPORT_FILE" << EOF
---
*🚀 Generated by the Comprehensive Multi-Stream Review System*
EOF
    
    log "Multi-stream report generated: $REPORT_FILE"
}

# Function to generate statistics
generate_statistics() {
    local reviews=("$@")
    local total_reviews=${#reviews[@]}
    local total_success=0
    
    log "Generating statistics for ${total_reviews} reviews"
    
    cat > "$STATS_FILE" << EOF
📊 Review Statistics
===================
Generated on $(date)

EOF

    for review in "${reviews[@]}"; do
        local result_file="${review}-review-results.txt"
        if [ -f "$result_file" ]; then
            total_success=$((total_success + 1))
            echo "✅ ${review^}: SUCCESS" >> "$STATS_FILE"
        else
            echo "❌ ${review^}: FAILED" >> "$STATS_FILE"
        fi
    done
    
    local success_rate
    if [ "$total_reviews" -gt 0 ]; then
        success_rate=$(awk "BEGIN {printf \"%.1f\", $total_success * 100 / $total_reviews}")
    else
        success_rate="N/A"
    fi
    
    cat >> "$STATS_FILE" << EOF

🎯 OVERALL RESULTS
================
Total Success Rate: ${total_success}/${total_reviews} (${success_rate}%)
EOF

    log "Statistics generated: $STATS_FILE"
    cat "$STATS_FILE"
}

# Main execution
main() {
    local mode="${1:-basic}"
    shift || true
    local reviews=("$@")
    
    case "$mode" in
        basic)
            generate_basic_report "${reviews[@]}"
            ;;
        multistream)
            generate_multistream_report
            ;;
        stats)
            generate_statistics "${reviews[@]}"
            ;;
        all)
            generate_basic_report "${reviews[@]}"
            generate_statistics "${reviews[@]}"
            ;;
        *)
            echo "Usage: $0 {basic|multistream|stats|all} [review1] [review2] ..." >&2
            echo "Environment variables:" >&2
            echo "  MAX_LINES=${MAX_LINES}" >&2
            echo "  REPORT_TITLE='${REPORT_TITLE}'" >&2
            echo "  REPORT_FILE=${REPORT_FILE}" >&2
            echo "  STATS_FILE=${STATS_FILE}" >&2
            exit 1
            ;;
    esac
}

# Run main function if script is executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi